services:
  ssh:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - USER_NAME=test
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=secret
      - SUDO_ACCESS=true
    ports:
      - "127.0.0.1:2222:2222"
    volumes:
      - ./logs:/config/logs
      - ./sshd_config/custom-init.sh:/custom-cont-init.d/99-custom.sh
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
